{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error signing up user: Username already exists","stack":"Error: Username already exists\n    at User.checkUserExistence (D:\\forex-remittance\\forex-remittance\\backend\\models\\User.js:50:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserController.signUp (D:\\forex-remittance\\forex-remittance\\backend\\controllers\\UserController.js:13:7)"}
{"level":"error","message":"Error signing up user: Username already exists","stack":"Error: Username already exists\n    at User.checkUserExistence (D:\\forex-remittance\\forex-remittance\\backend\\models\\User.js:50:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserController.signUp (D:\\forex-remittance\\forex-remittance\\backend\\controllers\\UserController.js:13:7)"}
{"code":"ECONNREFUSED","level":"error","message":"Error connecting to PostgreSQL database:","stack":"AggregateError\n    at D:\\Forex\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex\\forex-remittance\\backend\\database\\db.js:14:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex\\forex-remittance\\backend\\database\\db.js:14:20)"}
